version: '3'
services:

  front-react:
    image: front-react
    build:
      context: ./client

    environment:
      - PORT=3000
      - SERVER_PORT=5000
    depends_on:
      - server
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "3000:3000"

  server:
    image: server
    build:
      context: ./server

    environment:
      - PORT=5000
      - DB_URL=mongodb://localhost:27017/
      - DB_NAME=todo
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./server:/server
      - /server/node_modules


  mongo:
    image: mongo
    ports:
      - "27017:27017"